#[env]
#TERM = "xterm-256color"

[window]

opacity= 0.7
[window.padding]
x = 24
y = 15
[window.dimensions]
columns = 80
lines = 40

[scrolling]
history = 1_000
multiplier = 3

[font]
size = 13

  [font.normal]
  family = "JetBrains Mono"
  style = "Regular"

  [font.bold]
  family = "JetBrains Mono"
  style = "Bold"

  [font.italic]
  family = "JetBrains Mono"
  style = "Italic"

  [font.offset]
  y = 0#text = "CellForeground"


  [font.glyph_offset]
  y = 0

[colors.primary]
background = "0x282828"
foreground = "0xfdfdfd"

[colors.cursor]
cursor = "#a277ff"

[colors.search.matches]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.search.focused_match]
foreground = "0x1b1e28"
background = "0xadd7ff"


[colors.selection]
text = "CellForeground"
background = "#29263c"

#[colors.selection]
#text = "CellForeground"
#background = "0x303340"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black =  '0x1e2127'
red =    '0xe06c75'
green =  '0x98c379'
yellow = '0xd19a66'
blue =   '0x61afef'
magenta = '0xc678dd'
cyan =   '0x56b6c2'
white =  '0x828791'
[colors.bright]
black =   '0x5c6370'
red =     '0xe06c75'
green =   '0x98c379'
yellow =  '0xd19a66'
blue =    '0x61afef'
magenta = '0xc678dd'
cyan =    '0x56b6c2'
white =   '0xe6efff'

[cursor]
style = "Underline"
vi_mode_style = "Underline"
